/**
 * Component CRUD, validation, and generation for the Jekyll Component Framework.
 */

import path from "node:path";
import type { ServerContext } from "../server/context.js";
import { assertWriteAllowed } from "../server/context.js";
import { normalizeComponentName } from "../security/validation.js";
import {
  safeExists,
  safeReadFile,
  safeWriteFile,
  safeUnlink,
} from "../utils/filesystem.js";
import { analyzeLiquid, checkLiquidSyntax } from "../parsers/liquid-parser.js";
import { findImportForComponent } from "../parsers/scss-parser.js";
import { ProjectService } from "./project-service.js";
import { logger } from "../utils/logger.js";

export interface ComponentDescriptor {
  name: string;
  liquid?: string;
  scss?: string;
  javascript?: string;
  documentation?: string;
  example?: string;
}

export interface ComponentDetail extends ComponentDescriptor {
  liquidSource?: string;
  scssSource?: string;
  javascriptSource?: string;
  documentationSource?: string;
  parameters: ReturnType<typeof analyzeLiquid>["parameters"];
  variants: string[];
  accessibilityNotes: string[];
  classNames: string[];
}

export interface CreateComponentInput {
  name: string;
  category?: string;
  variants?: string[];
  javascript?: boolean;
  documentation?: boolean;
  example?: boolean;
  dry_run?: boolean;
}

export interface MutationResult {
  success: boolean;
  operation: string;
  component?: string;
  files_created?: string[];
  files_modified?: string[];
  dry_run?: boolean;
  operations?: Array<{ type: string; path: string }>;
  warnings?: string[];
  error?: { code: string; message: string; details?: unknown };
}

export interface ValidateResult {
  valid: boolean;
  component: string;
  errors: Array<{ file?: string; message: string }>;
  warnings: Array<{ file?: string; message: string }>;
}

function defaultLiquidTemplate(name: string, variants: string[]): string {
  const classBase = name;
  const variantList = variants.length ? variants.join(", ") : "default";
  return `{% comment %}
  Component: ${name}
  Description: Reusable ${name} component.
  Parameters:
    - label: Optional visible label; defaults to an empty string.
    - variant: Visual variant (${variantList}); defaults to "default".
    - class: Optional extra CSS classes; defaults to an empty string.
    - id: Optional HTML id; rendered only when provided.
    - content: Optional nested Liquid/HTML content.
  Usage: {% include components/${name}.html label="Click me" variant="default" %}
{% endcomment %}
{% assign variant = include.variant | default: "default" %}
{% assign label = include.label | default: "" %}
{% assign extra_class = include.class | default: "" %}
{% assign content = include.content | default: "" %}

<div class="${classBase} ${classBase}--{{ variant | escape }} {{ extra_class | escape }}"{% if include.id %} id="{{ include.id | escape }}"{% endif %}>
  {% if label != blank %}
    <span class="${classBase}__label">{{ label | escape }}</span>
  {% endif %}
  {% if content != blank %}
    <div class="${classBase}__content">{{ content }}</div>
  {% endif %}
</div>
`;
}

function defaultScssTemplate(name: string, variants: string[]): string {
  const lines = [
    `// Component: ${name}`,
    `.${name} {`,
    `  // Base styles`,
    ``,
    `  &__label {`,
    `    display: inline-block;`,
    `  }`,
    ``,
  ];
  for (const v of variants) {
    lines.push(`  &--${v} {`);
    lines.push(`    // variant: ${v}`);
    lines.push(`  }`);
    lines.push(``);
  }
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

function defaultDocsTemplate(name: string, variants: string[]): string {
  return `---
title: ${name}
---

# ${name}

## Overview

Reusable \`${name}\` component for the Jekyll Component Framework.

## Usage

\`\`\`liquid
{% include components/${name}.html label="Example" variant="default" %}
\`\`\`

## Parameters

| Name | Type | Default | Description |
|------|------|---------|-------------|
| label | string | \`""\` | Visible label text |
| variant | string | \`"default"\` | Visual variant |
| class | string | \`""\` | Extra CSS classes |
| id | string | — | Optional element id |
| content | string | — | Nested content |

## Variants

${variants.map((v) => `- \`${v}\``).join("\n")}

## Example

See \`examples/components/${name}.html\`.

## Accessibility

- Ensure interactive variants expose keyboard support and focus styles.
- Prefer semantic HTML over ARIA when possible.

## Notes

Generated by jekyll-component-mcp.
`;
}

function defaultExampleTemplate(name: string): string {
  return `---
layout: default
title: ${name} example
---

{% include components/${name}.html label="Example ${name}" variant="default" %}
`;
}

export class ComponentService {
  private project: ProjectService;

  constructor(private readonly ctx: ServerContext) {
    this.project = new ProjectService(ctx);
  }

  list(): ComponentDescriptor[] {
    const scan = this.project.getScan();
    return scan.components;
  }

  get(name: string): ComponentDetail | null {
    const normalized = normalizeComponentName(name);
    const scan = this.project.getScan();
    const desc = scan.components.find((c) => c.name === normalized);
    if (!desc) return null;

    const root = this.ctx.config.root;
    const maxSize = this.ctx.config.maxFileSize;

    let liquidSource: string | undefined;
    let scssSource: string | undefined;
    let javascriptSource: string | undefined;
    let documentationSource: string | undefined;

    if (desc.liquid && safeExists(root, desc.liquid)) {
      liquidSource = safeReadFile(root, desc.liquid, { maxSize });
    }
    if (desc.scss && safeExists(root, desc.scss)) {
      scssSource = safeReadFile(root, desc.scss, { maxSize });
    }
    if (desc.javascript && safeExists(root, desc.javascript)) {
      javascriptSource = safeReadFile(root, desc.javascript, { maxSize });
    }
    if (desc.documentation && safeExists(root, desc.documentation)) {
      documentationSource = safeReadFile(root, desc.documentation, { maxSize });
    }

    const analysis = liquidSource ? analyzeLiquid(liquidSource) : null;
    const variants: string[] = [];
    if (liquidSource) {
      const variantMatches = liquidSource.matchAll(/--([a-z0-9-]+)/gi);
      for (const m of variantMatches) {
        if (m[1] && !variants.includes(m[1])) variants.push(m[1]);
      }
    }
    if (scssSource) {
      const scssVars = scssSource.matchAll(/&--([a-z0-9-]+)/gi);
      for (const m of scssVars) {
        if (m[1] && !variants.includes(m[1])) variants.push(m[1]);
      }
    }

    return {
      ...desc,
      liquidSource,
      scssSource,
      javascriptSource,
      documentationSource,
      parameters: analysis?.parameters ?? [],
      variants: variants.length ? variants : ["default"],
      accessibilityNotes: analysis?.accessibilityHints ?? [],
      classNames: analysis?.classNames ?? [],
    };
  }

  create(input: CreateComponentInput): MutationResult {
    const name = normalizeComponentName(input.name);
    const variants = (input.variants?.length ? input.variants : ["default"]).map((v) =>
      v.toLowerCase().replace(/[^a-z0-9-]/g, "-"),
    );
    const dryRun = input.dry_run === true;
    const paths = this.ctx.config.paths;
    const root = this.ctx.config.root;

    try {
      assertWriteAllowed(this.ctx, "create");
    } catch (err) {
      return {
        success: false,
        operation: "component_create",
        error: {
          code: (err as { code?: string }).code ?? "WRITE_MODE_DENIED",
          message: (err as Error).message,
        },
      };
    }

    const liquidPath = path.posix.join(paths.components, `${name}.html`);
    const scssPath = path.posix.join(
      paths.scssComponents ?? path.posix.join(paths.scss, "components"),
      `_${name}.scss`,
    );
    const docsPath =
      input.documentation !== false
        ? path.posix.join(paths.docsComponents ?? path.posix.join(paths.docs, "components"), `${name}.md`)
        : null;
    const examplePath =
      input.example !== false
        ? path.posix.join(
            paths.examplesComponents ?? path.posix.join(paths.examples, "components"),
            `${name}.html`,
          )
        : null;
    const jsPath =
      input.javascript === true
        ? path.posix.join(paths.jsComponents ?? path.posix.join(paths.js, "components"), `${name}.js`)
        : null;

    const planned: Array<{ type: string; path: string }> = [
      { type: "create", path: liquidPath },
      { type: "create", path: scssPath },
    ];
    if (docsPath) planned.push({ type: "create", path: docsPath });
    if (examplePath) planned.push({ type: "create", path: examplePath });
    if (jsPath) planned.push({ type: "create", path: jsPath });

    // Check collisions
    const warnings: string[] = [];
    for (const p of planned) {
      if (safeExists(root, p.path)) {
        warnings.push(`File already exists and will be overwritten: ${p.path}`);
      }
    }

    if (dryRun) {
      return {
        success: true,
        operation: "component_create",
        component: name,
        dry_run: true,
        operations: planned,
        warnings,
      };
    }

    const filesCreated: string[] = [];
    const filesModified: string[] = [];

    try {
      const liquidResult = safeWriteFile(
        root,
        liquidPath,
        defaultLiquidTemplate(name, variants),
        { maxSize: this.ctx.config.maxFileSize },
      );
      if (liquidResult.created) filesCreated.push(liquidResult.path);
      else if (liquidResult.modified) filesModified.push(liquidResult.path);

      const scssResult = safeWriteFile(
        root,
        scssPath,
        defaultScssTemplate(name, variants),
        { maxSize: this.ctx.config.maxFileSize },
      );
      if (scssResult.created) filesCreated.push(scssResult.path);
      else if (scssResult.modified) filesModified.push(scssResult.path);

      if (docsPath) {
        const r = safeWriteFile(root, docsPath, defaultDocsTemplate(name, variants), {
          maxSize: this.ctx.config.maxFileSize,
        });
        if (r.created) filesCreated.push(r.path);
        else if (r.modified) filesModified.push(r.path);
      }

      if (examplePath) {
        const r = safeWriteFile(root, examplePath, defaultExampleTemplate(name), {
          maxSize: this.ctx.config.maxFileSize,
        });
        if (r.created) filesCreated.push(r.path);
        else if (r.modified) filesModified.push(r.path);
      }

      if (jsPath) {
        const r = safeWriteFile(
          root,
          jsPath,
          `// Component: ${name}\nexport function init${name.replace(/(^|-)(\w)/g, (_, __, c: string) => c.toUpperCase())}() {\n  // TODO\n}\n`,
          { maxSize: this.ctx.config.maxFileSize },
        );
        if (r.created) filesCreated.push(r.path);
        else if (r.modified) filesModified.push(r.path);
      }

      // Try to register SCSS import in common entry points
      this.ensureScssImport(name, scssPath, warnings);

      this.ctx.invalidateCache();
      logger.info("component_create", { name, filesCreated });

      return {
        success: true,
        operation: "component_create",
        component: name,
        files_created: filesCreated,
        files_modified: filesModified,
        warnings,
      };
    } catch (err) {
      return {
        success: false,
        operation: "component_create",
        component: name,
        error: {
          code: "CREATE_FAILED",
          message: (err as Error).message,
        },
      };
    }
  }

  private ensureScssImport(name: string, scssPath: string, warnings: string[]): void {
    const root = this.ctx.config.root;
    const paths = this.ctx.config.paths;
    const candidates = [
      path.posix.join(paths.scss, "components", "_index.scss"),
      path.posix.join(paths.scss, "_components.scss"),
      path.posix.join(paths.scss, "main.scss"),
      path.posix.join(paths.scss, "app.scss"),
      path.posix.join(paths.scss, "style.scss"),
      path.posix.join(paths.scss, "styles.scss"),
      path.posix.join(paths.scss, "index.scss"),
    ];

    for (const entry of candidates) {
      if (!safeExists(root, entry)) continue;
      try {
        const source = safeReadFile(root, entry, { maxSize: this.ctx.config.maxFileSize });
        const found = findImportForComponent(source, name);
        if (found.present) {
          logger.debug("SCSS import already present", { entry, name });
          return;
        }
        // Prefer @use with relative path from entry
        const entryDir = path.posix.dirname(entry);
        let importPath = path.posix.relative(entryDir, scssPath).replace(/\.scss$/, "");
        if (!importPath.startsWith(".")) importPath = `./${importPath}`;
        // Strip leading underscore for Sass convention
        importPath = importPath.replace(/\/_([^/]+)$/, "/$1");

        const line = `@use "${importPath}";\n`;
        const next = source.endsWith("\n") ? source + line : source + "\n" + line;
        safeWriteFile(root, entry, next, { maxSize: this.ctx.config.maxFileSize });
        warnings.push(`Added SCSS import to ${entry}`);
        return;
      } catch (err) {
        warnings.push(`Could not update SCSS entry ${entry}: ${(err as Error).message}`);
      }
    }
    warnings.push(
      "No SCSS entry point found to register the component import. Add the import manually.",
    );
  }

  validate(name: string): ValidateResult {
    const normalized = normalizeComponentName(name);
    const detail = this.get(normalized);
    const errors: ValidateResult["errors"] = [];
    const warnings: ValidateResult["warnings"] = [];

    if (!detail) {
      return {
        valid: false,
        component: normalized,
        errors: [{ message: `Component not found: ${normalized}` }],
        warnings: [],
      };
    }

    if (!detail.liquid) {
      errors.push({ message: "Missing Liquid include file" });
    } else if (detail.liquidSource) {
      const syntax = checkLiquidSyntax(detail.liquidSource);
      for (const e of syntax.errors) errors.push({ file: detail.liquid, message: e });
      for (const w of syntax.warnings) warnings.push({ file: detail.liquid, message: w });
      const analysis = analyzeLiquid(detail.liquidSource);
      for (const h of analysis.accessibilityHints) {
        warnings.push({ file: detail.liquid, message: h });
      }
      for (const parameter of analysis.parameters) {
        if (!parameter.hasDefault && !parameter.hasGuard) {
          warnings.push({
            file: detail.liquid,
            message: `include.${parameter.name} has no default fallback or if/unless guard`,
          });
        }
      }
    }

    if (!detail.scss) {
      warnings.push({ message: "No associated SCSS file detected" });
    } else {
      const expectedFilename = `_${normalized}.scss`;
      if (path.posix.basename(detail.scss) !== expectedFilename) {
        warnings.push({
          file: detail.scss,
          message: `SCSS filename should follow the BEM component name: ${expectedFilename}`,
        });
      }
      if (
        detail.scssSource &&
        !new RegExp(`\\.${normalized}(?:__[-\\w]+|--[-\\w]+)?\\s*(?:\\{|:)`).test(
          detail.scssSource,
        )
      ) {
        warnings.push({
          file: detail.scss,
          message: `SCSS should define a BEM selector beginning with .${normalized}`,
        });
      }
    }

    if (!detail.documentation) {
      warnings.push({ message: "No documentation file detected" });
    }

    return {
      valid: errors.length === 0,
      component: normalized,
      errors,
      warnings,
    };
  }

  delete(name: string, confirm: boolean): MutationResult {
    if (!confirm) {
      return {
        success: false,
        operation: "component_delete",
        error: {
          code: "CONFIRMATION_REQUIRED",
          message: "Destructive delete requires confirm: true",
        },
      };
    }

    try {
      assertWriteAllowed(this.ctx, "destructive");
    } catch (err) {
      return {
        success: false,
        operation: "component_delete",
        error: {
          code: (err as { code?: string }).code ?? "WRITE_MODE_DENIED",
          message: (err as Error).message,
        },
      };
    }

    const normalized = normalizeComponentName(name);
    const detail = this.get(normalized);
    if (!detail) {
      return {
        success: false,
        operation: "component_delete",
        error: { code: "NOT_FOUND", message: `Component not found: ${normalized}` },
      };
    }

    const root = this.ctx.config.root;
    const deleted: string[] = [];
    for (const key of ["liquid", "scss", "javascript", "documentation", "example"] as const) {
      const p = detail[key];
      if (p && safeExists(root, p)) {
        safeUnlink(root, p);
        deleted.push(p);
      }
    }

    this.ctx.invalidateCache();
    return {
      success: true,
      operation: "component_delete",
      component: normalized,
      files_modified: deleted,
    };
  }
}
